; pause.g
; called when a print from SD card is paused
;
; generated by RepRapFirmware Configuration Tool v3.3.2 on Mon Sep 06 2021 17:45:35 GMT+0200 (Mitteleuropäische Sommerzeit)
G1 Z15 ; move up to Z=15
;G1 X0 Y0 F6000 ; go to X=0 Y=0